import 'package:flutter/material.dart';

const List<IconData> cardIcons = <IconData>[
  Icons.sports_esports,
  Icons.gamepad,
  Icons.sports_soccer,
  Icons.hiking,
  Icons.pool,
  Icons.sports_score,
  Icons.sports_baseball,
  Icons.sailing,
  Icons.sports_tennis,
  Icons.videogame_asset,
  Icons.sports_gymnastics,
  Icons.surfing,
  Icons.sports_motorsports,
  Icons.sports_kabaddi,
  Icons.sports,
  Icons.golf_course,
  Icons.sports_volleyball,
  Icons.sports_baseball,
  Icons.sports_martial_arts,
  Icons.downhill_skiing,
  Icons.scoreboard,
  Icons.kayaking,
  Icons.sports_football,
  Icons.sports_handball,
  Icons.skateboarding,
  Icons.sports_golf,
  Icons.sports_cricket,
  Icons.nordic_walking,
  Icons.roller_skating,
  Icons.kitesurfing,
  Icons.sports_mma,
  Icons.paragliding,
  Icons.snowboarding,
  Icons.sports_hockey,
  Icons.snowshoeing,
  Icons.sports_rugby,
  Icons.sledding,
  Icons.snowmobile,
  Icons.fitness_center,
  Icons.emoji_events_rounded
];


  // Icons.celebration,
  // Icons.directions_car_filled,
  // Icons.directions_bike,
  // Icons.house,
  // Icons.local_shipping,
  // Icons.fastfood,
  // Icons.album_sharp,
  // Icons.forest,
  // Icons.anchor,
  // Icons.ac_unit,
  // Icons.android,
  // Icons.favorite,
  // Icons.light,
  // Icons.agriculture_sharp,
  // Icons.airplanemode_on,
  // Icons.umbrella,
  // Icons.alarm,
  // Icons.directions_subway_rounded,
  // Icons.person,
  // Icons.light_mode_outlined,
  // Icons.bedtime_sharp,
  // Icons.all_inclusive,
  // Icons.wine_bar,
  // Icons.star,
  // Icons.headset_rounded,
  // Icons.apple_sharp,
  // Icons.whatshot_outlined,
  // Icons.delete,
  // Icons.audiotrack_rounded,
  // Icons.back_hand_sharp,
  // Icons.visibility,
  // Icons.traffic_rounded,
  // Icons.beach_access_rounded,
  // Icons.battery_charging_full_sharp,
  // Icons.downhill_skiing_rounded,
  // Icons.directions_boat_rounded,
  // Icons.eco_sharp,
  // Icons.restaurant,
  // Icons.balance_sharp,
  // Icons.shopping_cart_rounded,
  // Icons.radar_sharp,
  // Icons.sports_esports_rounded,